AllCops:
  Exclude:
  - 'test.rb'

Metrics/MethodLength:
  Max: 23

Layout/LineLength:
  Max: 140

Metrics/ClassLength:
  Max: 260

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false
